### ISSUE TITLE
Function is not defined error

### ISSUE THREAD

**Issue by subu1979** [auth0/node-samlp#142]
Installed using the following command

npm install samlp

studio@Subramanyam CyLock_IDP % node server.js 
ReferenceError: Functions is not defined
    at Object.<anonymous> (/Users/studio/Desktop/CyLock_IDP/node_modules/xpath/xpath.js:3277:11)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/studio/Desktop/CyLock_IDP/node_modules/samlp/lib/samlp.js:3:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
studio@Subramanyam CyLock_IDP %

**Comment by subu1979** [comment]
i think, when we run inside "strict-mode" we are getting above error.
